env:
  cypress/globals: true
  es6: true
  es2020: true
extends:
  # I want to know the best practices for the settings here.
  # I don't know it, but this so many extends are enough to make it feel non-exemplary.
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:cypress/recommended
  - airbnb-typescript/base
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  project: ./tsconfig.json
plugins:
  - cypress
root: true
rules:
  import/extensions:
    - error
    - ignorePackages
    - ts: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - 'cypress/support/*.?s'
  import/order: warn
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
settings:
  import/resolver:
    node:
      path:
    typescript:
